### ISSUE TITLE
Wallet Address Difference Problem

### ISSUE THREAD

**Issue by sczhaiGA** [teamreflex/cosmo-web#16]
When I log in to apollo.cafe all the como counts, completed grids, and total special objects are all correct. For collections and in the profile it is connected to someone else's account, not mine, maybe because the wallet address in apollo.cafe is different from the one in my cosmo app.
![image](https://github.com/teamreflex/cosmo-web/assets/173596642/dc3a881a-620e-425c-9bce-738dd71b516c)

**Comment by kylekz** [comment]
This usually happens when someone does the delete account trick to change IDs, and ends up swapping IDs between accounts. Let me know your Cosmo ID, Polygon address and any previous IDs if this is something you've done, and I can manually fix it up. Feel free to message me on Discord too if you'd like: kairunz
